// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyActZALMqqxwSImOXIVEL7ZrmCcKDBxFrg',
    appId: '1:688114732007:web:89cf286c205eee24f0cb42',
    messagingSenderId: '688114732007',
    projectId: 'flutter-todo-bloc-app',
    authDomain: 'flutter-todo-bloc-app.firebaseapp.com',
    storageBucket: 'flutter-todo-bloc-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7ijwtwnzBY54UYlKP2eepBv0qRiwWt9o',
    appId: '1:688114732007:android:9bbbb0265c8b87b4f0cb42',
    messagingSenderId: '688114732007',
    projectId: 'flutter-todo-bloc-app',
    storageBucket: 'flutter-todo-bloc-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGHMnZ1MJ16PPmMNp4r1k-NVZ8duWtfWo',
    appId: '1:688114732007:ios:a8c40433db54f5e4f0cb42',
    messagingSenderId: '688114732007',
    projectId: 'flutter-todo-bloc-app',
    storageBucket: 'flutter-todo-bloc-app.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGHMnZ1MJ16PPmMNp4r1k-NVZ8duWtfWo',
    appId: '1:688114732007:ios:a8c40433db54f5e4f0cb42',
    messagingSenderId: '688114732007',
    projectId: 'flutter-todo-bloc-app',
    storageBucket: 'flutter-todo-bloc-app.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyActZALMqqxwSImOXIVEL7ZrmCcKDBxFrg',
    appId: '1:688114732007:web:94dfa978fc72dde3f0cb42',
    messagingSenderId: '688114732007',
    projectId: 'flutter-todo-bloc-app',
    authDomain: 'flutter-todo-bloc-app.firebaseapp.com',
    storageBucket: 'flutter-todo-bloc-app.firebasestorage.app',
  );
}
